name: Compilar APK con Buildozer

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias del sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-17-jdk autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libncursesw5-dev libffi-dev libssl-dev

      - name: Instalar Buildozer y Cython actualizados
        run: |
          pip install --upgrade pip
          pip install --upgrade cython buildozer flet fpdf2

      - name: Limpiar compilaciones anteriores
        run: buildozer android clean

      - name: Compilar APK
        run: buildozer -v android debug

      - name: Subir APK generado
        uses: actions/upload-artifact@v4
        with:
          name: paquete-apk
          path: bin/*.apk
